name: 'Fancy name of the action'
description: 'Short description'
author: 'name I want to become famous with'
inputs: # если нужны какие-то внешние параметры 
  exolve-token:
    description: 'This is a token to access github'
    required: true
  flag:
    description: 'This is flag that you can set to true or false'
    required: false
runs:
  using: 'node12' # необходимая версия ноды – важно
  main: 'actions/exolve-sms.js' # итоговый файл со всем кодом
branding: # как будет выглядеть иконка экшена в маркетплейсе
  icon: 'terminal'
  color: 'blue'
