name: 'Fancy name of the action'
description: 'Short description'
author: 'name I want to become famous with'
inputs: # если нужны какие-то внешние параметры 
  exolve-token:
    description: 'This is a token to access github'
    required: true
  receiver_phone:
    description: 'Target for message TeamLead or DevOps'
    required: true
  service_phone:
    description: 'Phone of MTC Exolve'
    required: true
  text:
    description: 'Text of SMS'
    required: true
runs:
  using: 'node12' # необходимая версия ноды – важно
  main: 'actions/exolve-sms.js' # итоговый файл со всем кодом
branding: # как будет выглядеть иконка экшена в маркетплейсе
  icon: 'terminal'
  color: 'blue'
