name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        working-directory: ./smsinfo
        run: dotnet restore
      - name: Build
        working-directory: ./smsinfo
        run: dotnet build --configuration Release --no-restore
      - name: Test
        working-directory: ./smsinfo
        run: dotnet test --no-restore --verbosity normal