name: "need to check pull request"
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1 шаг необходим, чтобы использовать экшен из соседней папки
      - name: Check out repository 
        uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag: 123
