name: "need to check pull request"
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    environment: habr
    steps:
      # 1 шаг необходим, чтобы использовать экшен из соседней папки
      - name: Check out repository 
        uses: actions/checkout@v3
      - name: Start message
        uses: ./
        with:
          exolve-token: ${{ secrets.EXOLVE_TOKEN }}
          receiver_phone:  ${{ env.DEVOPS_PHONE }}
          service_phone :  ${{ env.SERVICE_PHONE }}
          text: "Check pull request"
